create table if not exists clinica (
  user_id text primary key,
  nome text not null,
  slogan text not null,
  nutricionista text not null,
  crn text not null,
  contato text not null,
  cidade text not null,
  prot_g_kg double precision not null,
  gord_g_kg double precision not null,
  deficit_kcal integer not null,
  superavit_kcal integer not null,
  dias_reavaliacao integer not null
);

create table if not exists pacientes (
  id integer generated by default as identity primary key,
  user_id text not null,
  nome text not null,
  data_nascimento date,
  sexo text not null default '',
  genero text not null default '',
  cpf text not null default '',
  telefone text not null default '',
  email text not null default '',
  endereco text not null default '',
  altura_cm double precision,
  objetivo text not null default '',
  patologias text not null default '',
  alergias text not null default '',
  medicamentos text not null default '',
  antecedentes text not null default '',
  observacoes text not null default '',
  status text not null default 'Ativo',
  tipo_atendimento text not null default 'Presencial',
  atualizado_em timestamptz not null default now()
);
create index if not exists pacientes_user_idx on pacientes (user_id);

create table if not exists avaliacoes (
  id integer generated by default as identity primary key,
  user_id text not null,
  paciente_id integer not null,
  data date not null,
  peso double precision not null,
  altura double precision not null,
  cintura double precision,
  quadril double precision,
  atividade text not null,
  equipamento text not null default '',
  jejum text not null default '',
  sem_exercicio text not null default '',
  hidratacao text not null default '',
  gestante text not null default 'Não',
  lactante text not null default 'Não',
  imc double precision not null,
  tmb double precision not null,
  get_kcal double precision not null,
  kcal_meta double precision not null,
  prot_meta double precision not null,
  lip_meta double precision not null,
  carb_meta double precision not null,
  idade integer not null,
  diagnostico text not null default '',
  observacoes text not null default '',
  atualizado_em timestamptz not null default now()
);
create index if not exists avaliacoes_pac_idx on avaliacoes (user_id, paciente_id);

create table if not exists prescricoes (
  id integer generated by default as identity primary key,
  user_id text not null,
  paciente_id integer not null,
  titulo text not null,
  data date not null,
  situacao text not null default 'Rascunho',
  retorno_em date,
  kcal_meta double precision not null,
  prot_meta double precision not null,
  carb_meta double precision not null,
  lip_meta double precision not null,
  hidratacao text not null default '',
  emitida_em timestamptz,
  atualizado_em timestamptz not null default now()
);
create index if not exists prescricoes_pac_idx on prescricoes (user_id, paciente_id);

create table if not exists refeicoes (
  id integer generated by default as identity primary key,
  user_id text not null,
  prescricao_id integer not null,
  ordem integer not null,
  nome text not null,
  hora text not null default '',
  orientacao text not null default ''
);
create index if not exists refeicoes_presc_idx on refeicoes (user_id, prescricao_id);

create table if not exists itens (
  id integer generated by default as identity primary key,
  user_id text not null,
  prescricao_id integer not null,
  refeicao_id integer not null,
  ordem integer not null,
  alimento_id text not null,
  alimento_nome text not null,
  medida text not null,
  qtd double precision not null,
  gramas double precision not null,
  kcal double precision not null,
  ptn double precision not null,
  cho double precision not null,
  lip double precision not null,
  fibra double precision not null
);
create index if not exists itens_presc_idx on itens (user_id, prescricao_id);

create table if not exists agenda (
  id integer generated by default as identity primary key,
  user_id text not null,
  tipo text not null,
  titulo text not null,
  notas text not null default '',
  paciente_id integer,
  dia date not null,
  hora text,
  feito boolean not null default false,
  origem text not null default '',
  atualizado_em timestamptz not null default now()
);
create index if not exists agenda_user_dia_idx on agenda (user_id, dia);
