alter table avaliacoes add column if not exists gordura_pct double precision;
alter table avaliacoes add column if not exists massa_muscular double precision;

create table if not exists recordatorios (
  id integer generated by default as identity primary key,
  user_id text not null,
  paciente_id integer not null,
  data date not null,
  tipo text not null,
  queixa text not null default '',
  refeicoes jsonb not null default '[]',
  gosta text not null default '',
  nao_gosta text not null default '',
  alergias text not null default '',
  restricoes text not null default '',
  quem_cozinha text not null default '',
  rotina text not null default '',
  agua text not null default '',
  bebidas text not null default '',
  sono_apetite text not null default '',
  atividade text not null default '',
  suplementos text not null default '',
  digestao text not null default '',
  orcamento text not null default '',
  observacoes text not null default '',
  atualizado_em timestamptz not null default now()
);
create index if not exists recordatorios_pac_idx on recordatorios (user_id, paciente_id, data);
