create table if not exists exames (
  id integer generated by default as identity primary key,
  user_id text not null,
  paciente_id integer not null,
  data date not null,
  exame text not null,
  resultado text not null,
  unidade text not null default '',
  referencia text not null default '',
  fora_faixa boolean not null default false,
  situacao text not null default '',
  observacao text not null default '',
  atualizado_em timestamptz not null default now()
);
create index if not exists exames_pac_idx on exames (user_id, paciente_id, data);

create table if not exists documentos (
  id integer generated by default as identity primary key,
  user_id text not null,
  paciente_id integer not null,
  tipo text not null,
  titulo text not null,
  data date not null,
  situacao text not null default 'Rascunho',
  hora_inicio text not null default '',
  hora_fim text not null default '',
  destinatario text not null default '',
  valor text not null default '',
  referente text not null default '',
  motivo text not null default '',
  texto_livre text not null default '',
  texto text not null default '',
  emitido_em timestamptz,
  atualizado_em timestamptz not null default now()
);
create index if not exists documentos_pac_idx on documentos (user_id, paciente_id, data);
