create table if not exists referencias_exame (
  id integer generated by default as identity primary key,
  user_id text not null,
  ordem integer not null,
  nome text not null,
  unidade text not null default '',
  referencia text not null default ''
);
create index if not exists referencias_user_idx on referencias_exame (user_id, ordem);

create table if not exists modelos_documento (
  id integer generated by default as identity primary key,
  user_id text not null,
  chave text not null,
  titulo text not null,
  campos text not null default '',
  texto text not null,
  unique (user_id, chave)
);
