alter table clinica add column if not exists endereco text not null default '';
alter table clinica add column if not exists documento_emissor text not null default '';
alter table clinica add column if not exists adicional_gestante_t1 integer not null default 0;
alter table clinica add column if not exists adicional_gestante_t2 integer not null default 340;
alter table clinica add column if not exists adicional_gestante_t3 integer not null default 452;
alter table clinica add column if not exists adicional_lactante integer not null default 500;
alter table clinica add column if not exists variacao_bia double precision not null default 3;
alter table clinica add column if not exists variacao_agua double precision not null default 2;

alter table avaliacoes add column if not exists trimestre text not null default '';

create table if not exists listas (
  id integer generated by default as identity primary key,
  user_id text not null,
  lista text not null,
  ordem integer not null,
  valor text not null,
  extra text not null default ''
);
create index if not exists listas_user_idx on listas (user_id, lista, ordem);

create table if not exists profissionais (
  id integer generated by default as identity primary key,
  user_id text not null,
  nome text not null,
  crn text not null default '',
  cpf text not null default '',
  ativo boolean not null default false
);
create index if not exists profissionais_user_idx on profissionais (user_id);

create table if not exists alimentos_proprios (
  id integer generated by default as identity primary key,
  user_id text not null,
  nome text not null,
  grupo text not null default '',
  kcal double precision not null,
  ptn double precision not null default 0,
  cho double precision not null default 0,
  lip double precision not null default 0,
  fibra double precision not null default 0,
  medidas text not null default ''
);
create index if not exists alimentos_proprios_user_idx on alimentos_proprios (user_id);

create table if not exists modelos_cardapio (
  id integer generated by default as identity primary key,
  user_id text not null,
  titulo text not null,
  tema text not null default '',
  kcal_meta double precision not null default 0,
  prot_meta double precision not null default 0,
  carb_meta double precision not null default 0,
  lip_meta double precision not null default 0,
  hidratacao text not null default '',
  refeicoes jsonb not null default '[]'::jsonb,
  atualizado_em timestamptz not null default now()
);
create index if not exists modelos_cardapio_user_idx on modelos_cardapio (user_id);
