create table if not exists dietas (
  id integer generated by default as identity primary key,
  user_id text not null,
  paciente_id integer,
  tipo text not null,
  nome text not null,
  data date,
  indicacao text not null default '',
  kcal_meta double precision not null default 0,
  prot_meta double precision not null default 0,
  carb_meta double precision not null default 0,
  lip_meta double precision not null default 0,
  observacoes text not null default '',
  refeicoes jsonb not null default '[]'::jsonb,
  atualizado_em timestamptz not null default now()
);
create index if not exists dietas_user_idx on dietas (user_id, tipo, paciente_id);
