/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppSistemaRouteImport } from './routes/_app/sistema'
import { Route as PlanoTokenRouteImport } from './routes/plano.$token'
import { Route as AppPacientesIndexRouteImport } from './routes/_app/pacientes/index'
import { Route as AppPacientesPacienteIdRouteImport } from './routes/_app/pacientes/$pacienteId'
import { Route as ApiAgendaTokenRouteImport } from './routes/api/agenda/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppSistemaRoute = AppSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => AppRoute,
} as any)
const PlanoTokenRoute = PlanoTokenRouteImport.update({
  id: '/plano/$token',
  path: '/plano/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesPacienteIdRoute = AppPacientesPacienteIdRouteImport.update({
  id: '/pacientes/$pacienteId',
  path: '/pacientes/$pacienteId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAgendaTokenRoute = ApiAgendaTokenRouteImport.update({
  id: '/api/agenda/$token',
  path: '/api/agenda/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/sistema': typeof AppSistemaRoute
  '/plano/$token': typeof PlanoTokenRoute
  '/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/api/agenda/$token': typeof ApiAgendaTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/sistema': typeof AppSistemaRoute
  '/plano/$token': typeof PlanoTokenRoute
  '/': typeof AppIndexRoute
  '/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/api/agenda/$token': typeof ApiAgendaTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pacientes': typeof AppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/sistema': typeof AppSistemaRoute
  '/plano/$token': typeof PlanoTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/api/agenda/$token': typeof ApiAgendaTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/sistema'
    | '/plano/$token'
    | '/pacientes/$pacienteId'
    | '/api/agenda/$token'
    | '/api/auth/$'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agenda'
    | '/sistema'
    | '/plano/$token'
    | '/'
    | '/pacientes/$pacienteId'
    | '/api/agenda/$token'
    | '/api/auth/$'
    | '/pacientes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/sistema'
    | '/plano/$token'
    | '/_app/'
    | '/_app/pacientes/$pacienteId'
    | '/api/agenda/$token'
    | '/api/auth/$'
    | '/_app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlanoTokenRoute: typeof PlanoTokenRoute
  ApiAgendaTokenRoute: typeof ApiAgendaTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sistema': {
      id: '/_app/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof AppSistemaRouteImport
      parentRoute: typeof AppRoute
    }
    '/plano/$token': {
      id: '/plano/$token'
      path: '/plano/$token'
      fullPath: '/plano/$token'
      preLoaderRoute: typeof PlanoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pacientes/': {
      id: '/_app/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$pacienteId': {
      id: '/_app/pacientes/$pacienteId'
      path: '/pacientes/$pacienteId'
      fullPath: '/pacientes/$pacienteId'
      preLoaderRoute: typeof AppPacientesPacienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/agenda/$token': {
      id: '/api/agenda/$token'
      path: '/api/agenda/$token'
      fullPath: '/api/agenda/$token'
      preLoaderRoute: typeof ApiAgendaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppSistemaRoute: typeof AppSistemaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPacientesPacienteIdRoute: typeof AppPacientesPacienteIdRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppSistemaRoute: AppSistemaRoute,
  AppIndexRoute: AppIndexRoute,
  AppPacientesPacienteIdRoute: AppPacientesPacienteIdRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlanoTokenRoute: PlanoTokenRoute,
  ApiAgendaTokenRoute: ApiAgendaTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
